#STEP 1:BUILD VUE Project
FROM node:lts-alpine
RUN npm install -g http-server
RUN mkdir /app
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 80
CMD [ "http-server", "dist" ]
#STEP 2: CREATE NGINX SERVER
#FROM ngix:1.19.0-alpine AS prod-stage
#COPY --from=build /app/dist/usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx","-g","daemon off;"]